version: '3.4'
services:
  web_api:
    image: web_api
    container_name: sql_server_demo
    ports:
      - "5000:80"
  sql:
    image: "auctionservice"
    container_name: sql_server_demo
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=reallyStrongPwd123Valentina00
