// <auto-generated />
using System;
using AuctionService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionService.Migrations
{
    [DbContext(typeof(JavnoNadmetanjeContext))]
    partial class JavnoNadmetanjeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionService.Entities.JavnoNadmetanje", b =>
                {
                    b.Property<Guid>("javnoNadmetanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("adresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("brojUcesnika")
                        .HasColumnType("int");

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("izlicitiranaCena")
                        .HasColumnType("int");

                    b.Property<bool>("izuzeto")
                        .HasColumnType("bit");

                    b.Property<int>("krug")
                        .HasColumnType("int");

                    b.Property<Guid>("najboljiPonudjacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ovlascenoLiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("periodZakupa")
                        .HasColumnType("int");

                    b.Property<int>("pocetnaCenaPoHektaru")
                        .HasColumnType("int");

                    b.Property<Guid>("statusNadmetanjaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("tipID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("visinaDopuneDepozita")
                        .HasColumnType("int");

                    b.Property<DateTime>("vremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("vremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("javnoNadmetanjeID");

                    b.ToTable("javnaNadmetanja");

                    b.HasData(
                        new
                        {
                            javnoNadmetanjeID = new Guid("208a48a5-371c-4f9d-ac23-18bb176ff8f3"),
                            adresaID = new Guid("a06f99d2-0ba7-40ff-a241-304a03dfe4be"),
                            brojUcesnika = 10,
                            datum = new DateTime(2022, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            izlicitiranaCena = 7500,
                            izuzeto = false,
                            krug = 1,
                            najboljiPonudjacID = new Guid("8b3b7775-4293-4b41-9ccc-19f9cf694d68"),
                            ovlascenoLiceID = new Guid("5cfa282f-8324-4a8b-8c23-8d43502ca01e"),
                            periodZakupa = 12,
                            pocetnaCenaPoHektaru = 5000,
                            statusNadmetanjaID = new Guid("8aaa90c8-56f3-4a76-b07a-f895eded5a84"),
                            tipID = new Guid("4246a611-7b2f-429d-a9ba-0e539c81b82f"),
                            visinaDopuneDepozita = 500,
                            vremeKraja = new DateTime(2022, 2, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            vremePocetka = new DateTime(2022, 2, 17, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            javnoNadmetanjeID = new Guid("13d6ced2-ab84-4132-bf67-e96037f4813d"),
                            adresaID = new Guid("a06f99d2-0ba7-40ff-a241-304a03dfe4be"),
                            brojUcesnika = 10,
                            datum = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            izlicitiranaCena = 6000,
                            izuzeto = false,
                            krug = 1,
                            najboljiPonudjacID = new Guid("8b3b7775-4293-4b41-9ccc-19f9cf694d68"),
                            ovlascenoLiceID = new Guid("5cfa282f-8324-4a8b-8c23-8d43502ca01e"),
                            periodZakupa = 12,
                            pocetnaCenaPoHektaru = 4000,
                            statusNadmetanjaID = new Guid("8aaa90c8-56f3-4a76-b07a-f895eded5a84"),
                            tipID = new Guid("4246a611-7b2f-429d-a9ba-0e539c81b82f"),
                            visinaDopuneDepozita = 400,
                            vremeKraja = new DateTime(2022, 2, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            vremePocetka = new DateTime(2022, 2, 18, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AuctionService.Entities.Licitacija", b =>
                {
                    b.Property<Guid>("licitacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("broj")
                        .HasColumnType("int");

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("godina")
                        .HasColumnType("int");

                    b.Property<Guid>("javnoNadmetanjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("korakCene")
                        .HasColumnType("int");

                    b.Property<int>("ogranicenja")
                        .HasColumnType("int");

                    b.Property<DateTime>("rokZaDostavljanje")
                        .HasColumnType("datetime2");

                    b.HasKey("licitacijaID");

                    b.ToTable("licitacije");

                    b.HasData(
                        new
                        {
                            licitacijaID = new Guid("a215e4cb-a427-40cf-88b2-8488d140a939"),
                            broj = 1,
                            datum = new DateTime(2022, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            godina = 2022,
                            javnoNadmetanjeId = new Guid("208a48a5-371c-4f9d-ac23-18bb176ff8f3"),
                            korakCene = 100,
                            ogranicenja = 1,
                            rokZaDostavljanje = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            licitacijaID = new Guid("1de13266-85e8-4120-8b1f-daacc32c5811"),
                            broj = 2,
                            datum = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            godina = 2022,
                            javnoNadmetanjeId = new Guid("208a48a5-371c-4f9d-ac23-18bb176ff8f3"),
                            korakCene = 200,
                            ogranicenja = 1,
                            rokZaDostavljanje = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AuctionService.Entities.StatusNadmetanja", b =>
                {
                    b.Property<Guid>("statusNadmetanjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("statusNadmetanjaID");

                    b.ToTable("statusiNadmetanja");

                    b.HasData(
                        new
                        {
                            statusNadmetanjaID = new Guid("8aaa90c8-56f3-4a76-b07a-f895eded5a84"),
                            naziv = "Prvi krug"
                        },
                        new
                        {
                            statusNadmetanjaID = new Guid("b1ad846b-f76f-4485-8c89-08e2dfebd112"),
                            naziv = "Drugi krug sa starim uslovima"
                        },
                        new
                        {
                            statusNadmetanjaID = new Guid("d85b4a71-27e4-4626-9a3e-0412430e03d6"),
                            naziv = "Drugi krug sa novim uslovima"
                        });
                });

            modelBuilder.Entity("AuctionService.Entities.TipJavnogNadmetanja", b =>
                {
                    b.Property<Guid>("tipJavnogNadmetanjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nazivTipa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tipJavnogNadmetanjaID");

                    b.ToTable("tipoviNadmetanja");

                    b.HasData(
                        new
                        {
                            tipJavnogNadmetanjaID = new Guid("4246a611-7b2f-429d-a9ba-0e539c81b82f"),
                            nazivTipa = "Javna licitacija"
                        },
                        new
                        {
                            tipJavnogNadmetanjaID = new Guid("99b6d6ec-4358-4898-936b-31b31d236324"),
                            nazivTipa = "Otvaranje zatvorenih ponuda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
