// <auto-generated />
using System;
using AdresaService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdresaService.Migrations
{
    [DbContext(typeof(MestoContext))]
    [Migration("20230217155132_migracije")]
    partial class migracije
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdresaService.Entities.Adresa", b =>
                {
                    b.Property<Guid>("AdresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresaId");

                    b.ToTable("Adresa");

                    b.HasData(
                        new
                        {
                            AdresaId = new Guid("814f8e70-0edf-4cf5-8729-5091f7590b68"),
                            Mesto = "SM",
                            PostanskiBroj = 2200,
                            Ulica = "SAve kovacevica 25"
                        });
                });

            modelBuilder.Entity("AdresaService.Entities.Drzava", b =>
                {
                    b.Property<Guid>("DrzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrzavaId");

                    b.ToTable("Drzava");

                    b.HasData(
                        new
                        {
                            DrzavaId = new Guid("24742b99-32c6-4999-b0a7-757a178f9ee7"),
                            Naziv = "Srbija"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
